//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment() {
            this.upvotes = new HashSet<User>();
        }

        public int id { get; set; }
        public string comment { get; set; }
        //public string username { get; set; }
        //public Nullable<int> discriminator { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> upvotes { get; set; }
        public virtual User user { get; set; }
        public virtual Video video { get; set; }

        public string username { get; set; }
        public int discriminator { get; set; }
    }
}
