//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPAP
{
    using System;
    using MVCPAP.Models;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> video { get; set; }
        public string username { get; set; }
        public Nullable<int> discriminator { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<int> upvotes { get; set; }
        public Nullable<int> downvotes { get; set; }
    
        public virtual User User { get; set; }
        public virtual Video Video1 { get; set; }
    }
}
